# Generated by Django 3.1 on 2020-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ord',
            name='order',
        ),
        migrations.AddField(
            model_name='ord',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
