# Generated by Django 3.1 on 2020-03-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20200317_1618'),
        ('cart', '0002_auto_20200309_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ord',
            name='Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Address'),
        ),
        migrations.AddField(
            model_name='ord',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Payment'),
        ),
    ]
