# Generated by Django 3.1 on 2020-03-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='default.jpeg', upload_to='products/'),
        ),
    ]
