# Generated by Django 3.1 on 2020-03-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200313_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='/products/default.jpeg', upload_to='products/'),
        ),
    ]
