# Generated by Django 3.1 on 2020-03-17 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0006_remove_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='City',
            field=models.CharField(default='gurgaon', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='State',
            field=models.CharField(default='haryana', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('order_id', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
