# Generated by Django 3.1 on 2020-03-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20200317_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='/products/default.png', upload_to='products/'),
        ),
    ]
