# Generated by Django 3.1 on 2020-03-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20200318_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='First_Name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Last_Name',
        ),
    ]
